### ISSUE TITLE
Negative length container in records building

### ISSUE THREAD

**Issue by FaroutYLq** [FaroutYLq/saltax#66]
**Describe the bug**
Negative length container in records building shows up. Reasons uncleared. 

**To Reproduce**
Try salting `023747`.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._
```
Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processing/general.py", line 394, in touching_windows
    _check_objects_non_negative_length(objects)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processing/general.py", line 452, in _check_objects_non_negative_length
    assert mask
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuanlq/software/saltax/jobs/job.py", line 39, in <module>
    st.make(strrunid, 'event_basics')
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1426, in make
    for _ in self.get_iter(run_ids[0], targets,
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1336, in get_iter
    generator.throw(e)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/context.py", line 1307, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/chunk.py", line 304, in continuity_check
    for chunk in chunk_iter:
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processor.py", line 302, in iter
    raise exc.with_traceback(traceback)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 499, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/plugins/plugin.py", line 608, in do_compute
    result = self.compute(**kwargs)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen/plugins/peaks/peaks.py", line 44, in compute
    peaks = strax.replace_merged(peaklets[~is_s1], merged_s2s)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processing/peak_merging.py", line 110, in replace_merged
    skip_windows = strax.touching_windows(orig, merge)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax/processing/general.py", line 396, in touching_windows
    raise ValueError(f'{names} should have non-negative length!')
ValueError: containers should have non-negative length!
```

**Versions**
_Please add the output of:_
```
straxen.print_versions()
 module version                                                                               path  git
 python  3.9.18                          /opt/XENONnT/anaconda/envs/XENONnT_development/bin/python None
  strax   1.5.4   /opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/strax None
straxen   2.1.5 /opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.9/site-packages/straxen None
  cutax  1.15.5                                 /dali/lgrandi/xenonnt/software/cutax/v1.15.5/cutax None
```

All _italic_ comments can be removed from this template.

**Comment by FaroutYLq** [comment]
It is actually a problem in peak merging rather than records. Gonna close it.
